services:
  # Web Service
  - type: web
    name: class-notes-pwa
    runtime: node
    region: oregon # or your preferred region
    plan: free # or "starter" for production
    buildCommand: npm install && npm run build
    startCommand: node dist/app.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: class-notes-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
      # You'll need to add these in Render dashboard:
      # - AWS_REGION
      # - AWS_ACCESS_KEY_ID
      # - AWS_SECRET_ACCESS_KEY
      # - OPENAI_API_KEY
      # - GOOGLE_CLIENT_ID
      # - GOOGLE_CLIENT_SECRET
      # - GOOGLE_REDIRECT_URI (will be https://your-app.onrender.com/auth/google/callback)
    autoDeploy: true # Auto deploy on git push

databases:
  # PostgreSQL Database
  - name: class-notes-db
    databaseName: classnotes
    user: classnotes
    region: oregon # same as web service
    plan: free # or "starter" for production